#advanced version about pizza

print("Let's make a mad lib about pizza! First, give me an adjective!")
adj1 = input()
print("Alright, that's good, how about a nationality?")
nat = input()
print("Good one! Let's do a name!")
name = input()
print("That's lame, but whatever...noun, please?")
noun = input()
print("You're getting better at this, but that's not saying much...give me an adjective!")
adj2 = input()
print("Better, but not the best. Go ahead and give me another noun.")
noun2 = input()
print("Eh, not so sure about that but....give me an adjective.")
adj3 = input()
print("Sorry to be repetitive, but let's do another adjective!")
adj4 = input()
print("Really? That's original...plural noun, please.")
pluralnoun = input()
print("Mhmm, interesting. Just give me a plain old noun.")
noun3 = input()
print("Bare with me here! Give me a number!")
number = input()
print("This sounds weird, but give me a shape! I promise it will pay off...")
shape = input()
print("Give me a food, but obviously not pizza, okay?")
food = input()
print("Another food, preferably not pizza or the last food!")
food2 = input()
print("This is the last one I swear! Give me a number, any number!")
number2 = input()
print("Alright, are you ready for this?")
response = input()
print(str(response) + "?!! Well, I'm doing it regardless of your response anyways!")
print("Pizza was invented by a " + str(adj1) + " " + str(nat) + " chef named " + str(name) + ". To make a pizza, you need to take a lump of " + str(noun) + ", and make a thin, round " + str(adj2) + " " + str(noun2) + ". Then you cover it with " + str(adj3) + " sauce, " + str(noun2) + " cheese, and fresh chopped " + str(pluralnoun) + ". Next you have to bake it in a very hot " + str(noun3) + ". When it is done, cut it into " + str(number) + " " + str(shape) + " pieces. Some kids like " + str(food) + " pizza the best, but my favorite is the " + str(food2) + " pizza. If I could, I would eat pizza " + str(number2) + " times a day!")
