print("What's your name?")
name = input()
print("Hello, " + str(name) + " how old are you?")
age = input()
print(str(name) + ", what's your favorite breed of dog?")
breed = input()
print(str(name) + ", a corgi is far more superior than a " + str(breed) + " is! Only a " + str(age) + " year old would think that...")
